version: "3.9"

services:
  radiusdesk:
    image: radiusdesk/rdcore:latest
    container_name: radiusdesk
    env_file:
      - .radiusDeskEnv
    ports:
      - '80:80'
      - '1812:1812/udp'
      - '1813:1813/udp'
    networks:
      macvlan-net:
        ipv4_address: 192.168.150.250
      mariadb-net:
    labels:
      - com.host.description=radiusdesk

  rdmariadb:
    image: docker.io/bitnami/mariadb:10.5
    env_file:
      - .mariadbEnv
    volumes:
      - ${RADIUSDESK_VOLUME}/db_conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - rd_data:/bitnami/mariadb
      - ${RADIUSDESK_VOLUME}/db_startup:/tmp
    command: ["/bin/bash", "-c", "/tmp/startup.sh && /opt/bitnami/scripts/mariadb/entrypoint.sh /opt/bitnami/scripts/mariadb/run.sh"]
    networks:
      - mariadb-net
    labels:
      - com.host.description=mariadb-radiusdesk

volumes:
  rd_data:

networks:
  macvlan-net:
    external: true

  mariadb-net:
    driver: bridge